Check for error code

diff --git a/infrastructure/azure-pipelines.yml b/infrastructure/azure-pipelines.yml
--- a/infrastructure/azure-pipelines.yml
+++ b/infrastructure/azure-pipelines.yml
@@ -64,9 +64,15 @@ stages:
                   -var="resource_group_name=${AZURE_ENV_RG}" \
                   -out ${BUILD_BUILDNUMBER}.tfplan
                 terraform_exit_code=$?
+                set -e
+
                 echo "Terraform exit code: ${terraform_exit_code}"
                 echo "##vso[task.setvariable variable=TF_PLAN_CODE;issecret=false]${terraform_exit_code}"
-                set -e
+
+                # Terraform plan returns 1 on errors; other codes are forms of success
+                if [ ${terraform_exit_code} -eq 1 ]; then
+                  exit 1
+                fi
 
           - task: ArchiveFiles@2
             condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
